import Navbar from "@/components/navbar/navbar";
import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Aaron - Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="relative h-screen overflow-hidden">
          <span className="absolute -left-48 -top-48 -z-10 h-[500px] w-[500px] rounded-full bg-orange-500 bg-opacity-20 blur-3xl" />
          <Navbar />
          <span className="absolute -bottom-48 -right-48 -z-10 h-[500px] w-[500px] rounded-full bg-purple-500 bg-opacity-20 blur-3xl" />
          {children}
        </main>
      </body>
    </html>
  );
}
